# DCLV - burger dataset

In [1]:
# disable warnings
from warnings import simplefilter, filterwarnings
simplefilter(action='ignore', category=FutureWarning)
filterwarnings("ignore")

## burger dataset

In [2]:
# poison dataset
from clustvartools.datasets import burger
data = burger.data
data.info()

<class 'pandas.DataFrame'>
Index: 17 entries, BK__Double_Stacker to Tacos(2)
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Calories      17 non-null     float64
 1   Fat_Cal       17 non-null     float64
 2   Protein       17 non-null     float64
 3   Fat           17 non-null     float64
 4   Sat_Fat       17 non-null     float64
 5   Chol          17 non-null     float64
 6   Sodium        17 non-null     float64
 7   Carbs         17 non-null     float64
 8   Fiber         17 non-null     float64
 9   Sugar         17 non-null     float64
 10  Serving_size  17 non-null     int64
 11  Meat          17 non-null     str
dtypes: float64(10), int64(1), str(1)
memory usage: 1.7+ KB

## Instanciation and training

In [3]:
# instanciation
from clustvartools import DCLV
clf = DCLV(sup_var=(10,11),max_iter=0)

### `fit` function

In [4]:
# fit function
clf.fit(data)

DCLV(max_iter=0, sup_var=(10, 11))

### `fit_transform` function

In [5]:
# fit_transform function - squared loadings
sqload = clf.fit_transform(data)
sqload

                 1         2         3         4
Calories  0.919797  0.231570  0.268559  0.228457
Fat_Cal   0.983528  0.254750  0.259028  0.044410
Protein   0.146371  0.874634  0.325904  0.225763
Fat       0.977993  0.260903  0.259139  0.036632
Sat_Fat   0.285525  0.122074  0.767094  0.020755
Chol      0.291346  0.239043  0.584612  0.000738
Sodium    0.324749  0.874634  0.034576  0.051540
Carbs     0.174194  0.035779  0.008260  0.885070
Fiber     0.019814  0.012594  0.530460  0.018361
Sugar     0.020181  0.267489  0.023924  0.885070

### `transform` function

In [6]:
# transform function
sqload = clf.transform(burger.actif)
sqload

                 1         2         3         4
Calories  0.919797  0.231570  0.268559  0.228457
Fat_Cal   0.983528  0.254750  0.259028  0.044410
Protein   0.146371  0.874634  0.325904  0.225763
Fat       0.977993  0.260903  0.259139  0.036632
Sat_Fat   0.285525  0.122074  0.767094  0.020755
Chol      0.291346  0.239043  0.584612  0.000738
Sodium    0.324749  0.874634  0.034576  0.051540
Carbs     0.174194  0.035779  0.008260  0.885070
Fiber     0.019814  0.012594  0.530460  0.018361
Sugar     0.020181  0.267489  0.023924  0.885070

### `fit_predict` function

In [7]:
# fit_predict function
prediction = clf.fit_predict(data)
prediction.to_frame()

          cluster
Calories        1
Fat_Cal         1
Fat             1
Protein         2
Sodium          2
Sat_Fat         3
Fiber           3
Chol            3
Carbs           4
Sugar           4

### `predict` function

In [8]:
# predict function
prediction = clf.predict(burger.actif)
prediction.to_frame()

         cluster
Calories       1
Fat_Cal        1
Protein        2
Fat            1
Sat_Fat        3
Chol           3
Sodium         2
Carbs          4
Fiber          3
Sugar          4

In [9]:
# attributes
from clustvartools import sprintf
sprintf(clf)

**Clustering of Variables - DCLV**

*The results are available in the following objects:

name          description
------------  ------------------------------------
.call_        summary called parameters
.cluster_     results for clusters
.coef_        Coefficients
.quanti_var_  results for the continuous variables
.var_sup_     results for supplementary variables

## Cluster informations

In [10]:
# clusters informations
cluster = clf.cluster_
cluster._fields

('summary', 'princomps', 'cor', 'cortest')

### Cluster summary

In [11]:
# cluster summary
cluster_summary = clf.cluster_.summary
cluster_summary

,Cluster,Members,Variation Explained,Proportion Explained,Second Eigenvalue
0,1,3,2.881318,96.043932,0.118025
1,2,2,1.749269,87.463437,0.250731
2,3,3,1.882167,62.738886,0.726025
3,4,2,1.770141,88.507043,0.229859

### Inter-cluster correlations

In [12]:
# inter-cluster correlations
icor = cluster.cor
icor

          1         2         3         4
1  1.000000  0.509213  0.522391  0.297320
2  0.509213  1.000000  0.404625 -0.375403
3  0.522391  0.404625  1.000000  0.130506
4  0.297320 -0.375403  0.130506  1.000000

### Latent variables

In [13]:
# latent variables
princomps = cluster.princomps
princomps.head()

                                1         2         3         4
BK__Double_Stacker       1.887324  1.433125  2.466669 -0.694022
BK_CHICKENFRIES(12pc)    0.946785  2.562136 -0.922616 -0.825487
Buck_Double              0.095865  0.659589  1.511886 -0.649158
CHICKENTENDERS_Sandwich  1.581991 -0.441905 -0.192064 -0.261054
ChocolateFudgeSundae    -2.439858 -2.195092 -0.184349  1.946826

## Coefficients

In [14]:
# coefficients
coeffs = clf.coef_
coeffs._fields

('coef', 'coef_std')

### Coefficients of linear combinations

In [15]:
# coefficients of linear combinations
coef = coeffs.coef
coef

                  0          1          2         3
const     -4.521122  -3.158227  -1.154150 -2.132749
Calories   0.694704        NaN        NaN       NaN
Fat_Cal    1.116657        NaN        NaN       NaN
Protein         NaN  14.326400        NaN       NaN
Fat       10.063477        NaN        NaN       NaN
Sat_Fat         NaN        NaN  28.243842       NaN
Chol            NaN        NaN   2.587759       NaN
Sodium          NaN   0.350515        NaN       NaN
Carbs           NaN        NaN        NaN  6.701926
Fiber           NaN        NaN -81.589449       NaN
Sugar           NaN        NaN        NaN  7.789713

### Standardized scoring coefficients

In [16]:
# standardized scoring coefficients
coef_std = coeffs.coef_std
coef_std

                 0         1         2         3
Calories  0.332855       NaN       NaN       NaN
Fat_Cal   0.344193       NaN       NaN       NaN
Protein        NaN  0.534634       NaN       NaN
Fat       0.343223       NaN       NaN       NaN
Sat_Fat        NaN       NaN  0.465336       NaN
Chol           NaN       NaN  0.406234       NaN
Sodium         NaN  0.534634       NaN       NaN
Carbs          NaN       NaN       NaN  0.531473
Fiber          NaN       NaN -0.386962       NaN
Sugar          NaN       NaN       NaN  0.531473

## Variables informations

In [17]:
# variables informations
var_ = clf.quanti_var_
var_._fields

('cluster', 'cor', 'cortest', 'sqload', 'member', 'sim', 'loadings')

### Variables loadings (=eigenvectors)

In [18]:
# variables loadings
var_.loadings

                 0         1         2         3
Calories  0.565002       NaN       NaN       NaN
Fat_Cal   0.584249       NaN       NaN       NaN
Protein        NaN  0.707107       NaN       NaN
Fat       0.582602       NaN       NaN       NaN
Sat_Fat        NaN       NaN  0.638404       NaN
Chol           NaN       NaN  0.557320       NaN
Sodium         NaN  0.707107       NaN       NaN
Carbs          NaN       NaN       NaN  0.707107
Fiber          NaN       NaN -0.530881       NaN
Sugar          NaN       NaN       NaN  0.707107

### Cluster correlations - Structure

In [19]:
# cluster correlation
var_.cor

                 1         2         3         4
Calories  0.959060  0.481217  0.518226  0.477971
Fat_Cal   0.991730  0.504728  0.508948  0.210736
Protein   0.382585  0.935219  0.570880 -0.475146
Fat       0.988935  0.510787  0.509057  0.191396
Sat_Fat   0.534346  0.349391  0.875839  0.144068
Chol      0.539765  0.488920  0.764599  0.027157
Sodium    0.569867  0.935219  0.185946 -0.227023
Carbs     0.417366 -0.189153  0.090883  0.940782
Fiber    -0.140763 -0.112222 -0.728327 -0.135502
Sugar     0.142061 -0.517193  0.154672  0.940782

### Cluster relationship with variables

In [20]:
# cluster relationship
var_.cortest

    variable  cluster         r      r**2          t      Pr(>|t|)
0   Calories        1  0.959060  0.919797  13.115819  1.270734e-09
1   Calories        2  0.481217  0.231570   2.126106  5.050745e-02
2   Calories        3  0.518226  0.268559   2.346796  3.308355e-02
3   Calories        4  0.477971  0.228457   2.107498  5.231158e-02
4    Fat_Cal        1  0.991730  0.983528  29.927603  8.616850e-15
5    Fat_Cal        2  0.504728  0.254750   2.264395  3.879919e-02
6    Fat_Cal        3  0.508948  0.259028   2.289906  3.693754e-02
7    Fat_Cal        4  0.210736  0.044410   0.834927  4.168590e-01
8    Protein        1  0.382585  0.146371   1.603757  1.296116e-01
9    Protein        2  0.935219  0.874634  10.229859  3.702461e-08
10   Protein        3  0.570880  0.325904   2.692957  1.669282e-02
11   Protein        4 -0.475146  0.225763  -2.091393  5.392089e-02
12       Fat        1  0.988935  0.977993  25.818509  7.588483e-14
13       Fat        2  0.510787  0.260903   2.301096  3.614765e-02
14       Fat        3  0.509057  0.259139   2.290573  3.689000e-02
15       Fat        4  0.191396  0.036632   0.755234  4.618035e-01
16   Sat_Fat        1  0.534346  0.285525   2.448356  2.712886e-02
17   Sat_Fat        2  0.349391  0.122074   1.444203  1.692446e-01
18   Sat_Fat        3  0.875839  0.767094   7.028779  4.079579e-06
19   Sat_Fat        4  0.144068  0.020755   0.563854  5.811866e-01
20      Chol        1  0.539765  0.291346   2.483322  2.532527e-02
21      Chol        2  0.488920  0.239043   2.170717  4.641340e-02
22      Chol        3  0.764599  0.584612   4.594652  3.506817e-04
23      Chol        4  0.027157  0.000738   0.105218  9.175969e-01
24    Sodium        1  0.569867  0.324749   2.685880  1.693122e-02
25    Sodium        2  0.935219  0.874634  10.229859  3.702461e-08
26    Sodium        3  0.185946  0.034576   0.732950  4.748881e-01
27    Sodium        4 -0.227023  0.051540  -0.902830  3.808858e-01
28     Carbs        1  0.417366  0.174194   1.778786  9.554320e-02
29     Carbs        2 -0.189153  0.035779  -0.746053  4.671674e-01
30     Carbs        3  0.090883  0.008260   0.353453  7.286676e-01
31     Carbs        4  0.940782  0.885070  10.747777  1.919320e-08
32     Fiber        1 -0.140763  0.019814  -0.550656  5.899771e-01
33     Fiber        2 -0.112222  0.012594  -0.437395  6.680568e-01
34     Fiber        3 -0.728327  0.530460  -4.116573  9.150036e-04
35     Fiber        4 -0.135502  0.018361  -0.529684  6.040831e-01
36     Sugar        1  0.142061  0.020181   0.555838  5.865176e-01
37     Sugar        2 -0.517193  0.267489  -2.340405  3.349684e-02
38     Sugar        3  0.154672  0.023924   0.606341  5.533550e-01
39     Sugar        4  0.940782  0.885070  10.747777  1.919320e-08

### Squared Loadings (=correlation ratio)

In [21]:
# squared loadings
var_.sqload

                 1         2         3         4
Calories  0.919797  0.231570  0.268559  0.228457
Fat_Cal   0.983528  0.254750  0.259028  0.044410
Protein   0.146371  0.874634  0.325904  0.225763
Fat       0.977993  0.260903  0.259139  0.036632
Sat_Fat   0.285525  0.122074  0.767094  0.020755
Chol      0.291346  0.239043  0.584612  0.000738
Sodium    0.324749  0.874634  0.034576  0.051540
Carbs     0.174194  0.035779  0.008260  0.885070
Fiber     0.019814  0.012594  0.530460  0.018361
Sugar     0.020181  0.267489  0.023924  0.885070

### Cluster member

In [22]:
# cluster member
var_.member.sort_values(by=["Cluster","Variable"])

   Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
0  Calories       1    0.919797     0.268559       0.109651
3       Fat       1    0.977993     0.260903       0.029776
1   Fat_Cal       1    0.983528     0.259028        0.02223
2   Protein       2    0.874634     0.325904       0.185976
6    Sodium       2    0.874634     0.324749       0.185658
5      Chol       3    0.584612     0.291346       0.586165
8     Fiber       3     0.53046     0.019814       0.479031
4   Sat_Fat       3    0.767094     0.285525       0.325982
7     Carbs       4     0.88507     0.174194       0.139173
9     Sugar       4     0.88507     0.267489       0.156898

## Supplementary variables informations

In [23]:
# supplementary variables informations
var_sup_ = clf.var_sup_
var_sup_._fields

('cluster', 'cor', 'cortest', 'sqload', 'member')

### Cluster

In [24]:
# cluster
var_sup_.cluster.to_frame()

             cluster
Serving_size       4
Meat               2

### Cluster correlations

In [25]:
# cluster correlations
var_sup_.cor

                     1         2         3         4
Serving_size -0.157144  0.345107  0.187181 -0.471995

### Cluster relationship

In [26]:
# cluster relationship
var_sup_.cortest

       variable  cluster         r      r**2         t  Pr(>|t|)
0  Serving_size        1 -0.157144  0.024694 -0.616273  0.546954
1  Serving_size        2  0.345107  0.119099  1.424084  0.174892
2  Serving_size        3  0.187181  0.035037  0.737992  0.471908
3  Serving_size        4 -0.471995  0.222780 -2.073534  0.055758

### Squared loadings

In [27]:
# squared loadings - supplementary variables
var_sup_.sqload

                     1         2         3         4
Serving_size  0.024694  0.119099  0.035037  0.222780
Meat          0.155931  0.663742  0.056768  0.308204

### Cluster member

In [28]:
# cluster member
var_sup_.member.sort_values(by=["Cluster","Variable"])

       Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
1          Meat       2    0.663742     0.308204       0.486066
0  Serving_size       4     0.22278     0.119099       0.882301

## Summary

In [29]:
# summary
from clustvartools import summary
summary(clf)

                     Clustering of Variables - DCLV Results

Cluster Summary for 4 Clusters:
  Cluster  Members  Variation Explained  Proportion Explained  \
0       1        3             2.881318             96.043932
1       2        2             1.749269             87.463437
2       3        3             1.882167             62.738886
3       4        2             1.770141             88.507043

   Second Eigenvalue
0           0.118025
1           0.250731
2           0.726025
3           0.229859

Inter-cluster Correlations:
          1         2         3         4
1  1.000000  0.509213  0.522391  0.297320
2  0.509213  1.000000  0.404625 -0.375403
3  0.522391  0.404625  1.000000  0.130506
4  0.297320 -0.375403  0.130506  1.000000

Cluster R-square:
               1       2       3       4
Calories  0.9198  0.2316  0.2686  0.2285
Fat_Cal   0.9835  0.2548  0.2590  0.0444
Protein   0.1464  0.8746  0.3259  0.2258
Fat       0.9780  0.2609  0.2591  0.0366
Sat_Fat   0.2855  0.1221  0.7671  0.0208
Chol      0.2913  0.2390  0.5846  0.0007
Sodium    0.3247  0.8746  0.0346  0.0515
Carbs     0.1742  0.0358  0.0083  0.8851
Fiber     0.0198  0.0126  0.5305  0.0184
Sugar     0.0202  0.2675  0.0239  0.8851

Cluster Members and R-square values:
   Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
0  Calories       1    0.919797     0.268559       0.109651
1   Fat_Cal       1    0.983528     0.259028        0.02223
2   Protein       2    0.874634     0.325904       0.185976
3       Fat       1    0.977993     0.260903       0.029776
4   Sat_Fat       3    0.767094     0.285525       0.325982
5      Chol       3    0.584612     0.291346       0.586165
6    Sodium       2    0.874634     0.324749       0.185658
7     Carbs       4     0.88507     0.174194       0.139173
8     Fiber       3     0.53046     0.019814       0.479031
9     Sugar       4     0.88507     0.267489       0.156898

Cluster R-square - Supplementary variables:
                   1       2       3       4
Serving_size  0.0247  0.1191  0.0350  0.2228
Meat          0.1559  0.6637  0.0568  0.3082

Cluster Members and R-square values - Supplementary variables:
       Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
0  Serving_size       4     0.22278     0.119099       0.882301
1          Meat       2    0.663742     0.308204       0.486066

In [30]:
# summary with detailed
summary(clf,detailed=True)

                     Clustering of Variables - DCLV Results

Cluster Summary for 4 Clusters:
  Cluster  Members  Variation Explained  Proportion Explained  \
0       1        3             2.881318             96.043932
1       2        2             1.749269             87.463437
2       3        3             1.882167             62.738886
3       4        2             1.770141             88.507043

   Second Eigenvalue
0           0.118025
1           0.250731
2           0.726025
3           0.229859

Inter-cluster Correlations:
          1         2         3         4
1  1.000000  0.509213  0.522391  0.297320
2  0.509213  1.000000  0.404625 -0.375403
3  0.522391  0.404625  1.000000  0.130506
4  0.297320 -0.375403  0.130506  1.000000

Linear coefficients:
                  0          1          2         3
const     -4.521122  -3.158227  -1.154150 -2.132749
Calories   0.694704        NaN        NaN       NaN
Fat_Cal    1.116657        NaN        NaN       NaN
Protein         NaN  14.326400        NaN       NaN
Fat       10.063477        NaN        NaN       NaN
Sat_Fat         NaN        NaN  28.243842       NaN
Chol            NaN        NaN   2.587759       NaN
Sodium          NaN   0.350515        NaN       NaN
Carbs           NaN        NaN        NaN  6.701926
Fiber           NaN        NaN -81.589449       NaN
Sugar           NaN        NaN        NaN  7.789713

Standardized scoring coefficients:
                 0         1         2         3
Calories  0.332855       NaN       NaN       NaN
Fat_Cal   0.344193       NaN       NaN       NaN
Protein        NaN  0.534634       NaN       NaN
Fat       0.343223       NaN       NaN       NaN
Sat_Fat        NaN       NaN  0.465336       NaN
Chol           NaN       NaN  0.406234       NaN
Sodium         NaN  0.534634       NaN       NaN
Carbs          NaN       NaN       NaN  0.531473
Fiber          NaN       NaN -0.386962       NaN
Sugar          NaN       NaN       NaN  0.531473

Cluster R-square:
               1       2       3       4
Calories  0.9198  0.2316  0.2686  0.2285
Fat_Cal   0.9835  0.2548  0.2590  0.0444
Protein   0.1464  0.8746  0.3259  0.2258
Fat       0.9780  0.2609  0.2591  0.0366
Sat_Fat   0.2855  0.1221  0.7671  0.0208
Chol      0.2913  0.2390  0.5846  0.0007
Sodium    0.3247  0.8746  0.0346  0.0515
Carbs     0.1742  0.0358  0.0083  0.8851
Fiber     0.0198  0.0126  0.5305  0.0184
Sugar     0.0202  0.2675  0.0239  0.8851

Cluster Members and R-square values:
   Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
0  Calories       1    0.919797     0.268559       0.109651
1   Fat_Cal       1    0.983528     0.259028        0.02223
2   Protein       2    0.874634     0.325904       0.185976
3       Fat       1    0.977993     0.260903       0.029776
4   Sat_Fat       3    0.767094     0.285525       0.325982
5      Chol       3    0.584612     0.291346       0.586165
6    Sodium       2    0.874634     0.324749       0.185658
7     Carbs       4     0.88507     0.174194       0.139173
8     Fiber       3     0.53046     0.019814       0.479031
9     Sugar       4     0.88507     0.267489       0.156898

Cluster R-square - Supplementary variables:
                   1       2       3       4
Serving_size  0.0247  0.1191  0.0350  0.2228
Meat          0.1559  0.6637  0.0568  0.3082

Cluster Members and R-square values - Supplementary variables:
       Variable Cluster Own Cluster Next Closest 1 - R**2 Ratio
0  Serving_size       4     0.22278     0.119099       0.882301
1          Meat       2    0.663742     0.308204       0.486066

In [31]:
# markdown formatting
summary(clf,to_markdown=True)

                     Clustering of Variables - DCLV Results

Cluster Summary for 4 Clusters:
      Cluster    Members    Variation Explained    Proportion Explained    Second Eigenvalue
--  ---------  ---------  ---------------------  ----------------------  -------------------
 0          1          3                2.88132                 96.0439             0.118025
 1          2          2                1.74927                 87.4634             0.250731
 2          3          3                1.88217                 62.7389             0.726025
 3          4          2                1.77014                 88.507              0.229859

Inter-cluster Correlations:
           1          2         3          4
--  --------  ---------  --------  ---------
 1  1          0.509213  0.522391   0.29732
 2  0.509213   1         0.404625  -0.375403
 3  0.522391   0.404625  1          0.130506
 4  0.29732   -0.375403  0.130506   1

Cluster R-square:
               1       2       3       4
--------  ------  ------  ------  ------
Calories  0.9198  0.2316  0.2686  0.2285
Fat_Cal   0.9835  0.2548  0.259   0.0444
Protein   0.1464  0.8746  0.3259  0.2258
Fat       0.978   0.2609  0.2591  0.0366
Sat_Fat   0.2855  0.1221  0.7671  0.0208
Chol      0.2913  0.239   0.5846  0.0007
Sodium    0.3247  0.8746  0.0346  0.0515
Carbs     0.1742  0.0358  0.0083  0.8851
Fiber     0.0198  0.0126  0.5305  0.0184
Sugar     0.0202  0.2675  0.0239  0.8851

Cluster Members and R-square values:
    Variable      Cluster    Own Cluster    Next Closest    1 - R**2 Ratio
--  ----------  ---------  -------------  --------------  ----------------
 0  Calories            1       0.919797       0.268559          0.109651
 1  Fat_Cal             1       0.983528       0.259028          0.0222296
 2  Protein             2       0.874634       0.325904          0.185976
 3  Fat                 1       0.977993       0.260903          0.0297758
 4  Sat_Fat             3       0.767094       0.285525          0.325982
 5  Chol                3       0.584612       0.291346          0.586165
 6  Sodium              2       0.874634       0.324749          0.185658
 7  Carbs               4       0.88507        0.174194          0.139173
 8  Fiber               3       0.53046        0.0198143         0.479031
 9  Sugar               4       0.88507        0.267489          0.156898

Cluster R-square - Supplementary variables:
                   1       2       3       4
------------  ------  ------  ------  ------
Serving_size  0.0247  0.1191  0.035   0.2228
Meat          0.1559  0.6637  0.0568  0.3082

Cluster Members and R-square values - Supplementary variables:
    Variable        Cluster    Own Cluster    Next Closest    1 - R**2 Ratio
--  ------------  ---------  -------------  --------------  ----------------
 0  Serving_size          4       0.22278         0.119099          0.882301
 1  Meat                  2       0.663742        0.308204          0.486066

In [32]:
# markdown formatting
summary(clf,detailed=True,to_markdown=True)

                     Clustering of Variables - DCLV Results

Cluster Summary for 4 Clusters:
      Cluster    Members    Variation Explained    Proportion Explained    Second Eigenvalue
--  ---------  ---------  ---------------------  ----------------------  -------------------
 0          1          3                2.88132                 96.0439             0.118025
 1          2          2                1.74927                 87.4634             0.250731
 2          3          3                1.88217                 62.7389             0.726025
 3          4          2                1.77014                 88.507              0.229859

Inter-cluster Correlations:
           1          2         3          4
--  --------  ---------  --------  ---------
 1  1          0.509213  0.522391   0.29732
 2  0.509213   1         0.404625  -0.375403
 3  0.522391   0.404625  1          0.130506
 4  0.29732   -0.375403  0.130506   1

Linear coefficients:
                   0           1          2          3
--------  ----------  ----------  ---------  ---------
const      -4.52112    -3.15823    -1.15415   -2.13275
Calories    0.694704  nan         nan        nan
Fat_Cal     1.11666   nan         nan        nan
Protein   nan          14.3264    nan        nan
Fat        10.0635    nan         nan        nan
Sat_Fat   nan         nan          28.2438   nan
Chol      nan         nan           2.58776  nan
Sodium    nan           0.350515  nan        nan
Carbs     nan         nan         nan          6.70193
Fiber     nan         nan         -81.5894   nan
Sugar     nan         nan         nan          7.78971

Standardized scoring coefficients:
                   0           1           2           3
--------  ----------  ----------  ----------  ----------
Calories    0.332855  nan         nan         nan
Fat_Cal     0.344193  nan         nan         nan
Protein   nan           0.534634  nan         nan
Fat         0.343223  nan         nan         nan
Sat_Fat   nan         nan           0.465336  nan
Chol      nan         nan           0.406234  nan
Sodium    nan           0.534634  nan         nan
Carbs     nan         nan         nan           0.531473
Fiber     nan         nan          -0.386962  nan
Sugar     nan         nan         nan           0.531473

Cluster R-square:
               1       2       3       4
--------  ------  ------  ------  ------
Calories  0.9198  0.2316  0.2686  0.2285
Fat_Cal   0.9835  0.2548  0.259   0.0444
Protein   0.1464  0.8746  0.3259  0.2258
Fat       0.978   0.2609  0.2591  0.0366
Sat_Fat   0.2855  0.1221  0.7671  0.0208
Chol      0.2913  0.239   0.5846  0.0007
Sodium    0.3247  0.8746  0.0346  0.0515
Carbs     0.1742  0.0358  0.0083  0.8851
Fiber     0.0198  0.0126  0.5305  0.0184
Sugar     0.0202  0.2675  0.0239  0.8851

Cluster Members and R-square values:
    Variable      Cluster    Own Cluster    Next Closest    1 - R**2 Ratio
--  ----------  ---------  -------------  --------------  ----------------
 0  Calories            1       0.919797       0.268559          0.109651
 1  Fat_Cal             1       0.983528       0.259028          0.0222296
 2  Protein             2       0.874634       0.325904          0.185976
 3  Fat                 1       0.977993       0.260903          0.0297758
 4  Sat_Fat             3       0.767094       0.285525          0.325982
 5  Chol                3       0.584612       0.291346          0.586165
 6  Sodium              2       0.874634       0.324749          0.185658
 7  Carbs               4       0.88507        0.174194          0.139173
 8  Fiber               3       0.53046        0.0198143         0.479031
 9  Sugar               4       0.88507        0.267489          0.156898

Cluster R-square - Supplementary variables:
                   1       2       3       4
------------  ------  ------  ------  ------
Serving_size  0.0247  0.1191  0.035   0.2228
Meat          0.1559  0.6637  0.0568  0.3082

Cluster Members and R-square values - Supplementary variables:
    Variable        Cluster    Own Cluster    Next Closest    1 - R**2 Ratio
--  ------------  ---------  -------------  --------------  ----------------
 0  Serving_size          4       0.22278         0.119099          0.882301
 1  Meat                  2       0.663742        0.308204          0.486066